### ISSUE TITLE
mark with virtual text

### ISSUE THREAD

**Issue by skimask9** [aidancz/eolmark.nvim#1]
Would it be possible to fix eolmark with virtual text, because it blocks suggestions .
![image](https://github.com/user-attachments/assets/7f381500-249d-4968-aa95-1a078dc7000c)
![image](https://github.com/user-attachments/assets/515f3e10-28d8-4bef-a9c4-f10018a595fc)

**Comment by aidancz** [comment]
thank you for the issue!

this has been fixed in the latest version (by setting `priority` to 0), you may adjust priority to another value

please look through the newer `readme` for details
